version: '2'

services:
  database:
    image: mariadb
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=duolctxen
    networks:
      nextcloud:
        aliases:
          - database
    volumes:
      - /mnt/Configs/next/database:/var/lib/mysql
    restart: always

  nexcloud:
    image: nextcloud
    networks:
      nextcloud:
        aliases:
          - nextcloud
    ports:
      - "80:80"
    volumes:
      - /mnt/Configs/next:/var/www/html
      - /mnt/Nextcloud:/var/www/html/data
    links:
      - database
    restart: always

networks:
  nextcloud:
